services:
  app:
    build: .
    container_name: ecommerce_app
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ecommerce
      DB_USER: ecommerce
      DB_PASSWORD: strongpassword

  db:
    image: mysql:8.0
    container_name: ecommerce_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: strongpassword

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
